#:schema https://raw.githubusercontent.com/cloudflare/workers-sdk/main/packages/wrangler/config-schema.json
name = "intelligentalgorithmwebsite"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

[pages_build_output_config]
static_dir = "dist"
